<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['edition_app_description'] = 'Менеджер по Выпуску обеспечивает быстрый способ обновления от Сообщества до Профессионала в новой установке.';
$lang['edition_app_name'] = 'Менеджер по выпуску';
$lang['edition_select_edition'] = 'Выберите издание';
