#!/bin/sh

if [ -e /etc/clearos/edition/business-7.1.conf ]; then
    logger -p local6.notice -t installer "app-edition-core - removing Business 7.1 definition"
    rm -rf /etc/clearos/edition/business-7.1.conf
fi
if [ -e /etc/clearos/edition/home-7.1.conf ]; then
    logger -p local6.notice -t installer "app-edition-core - removing Home 7.1 definition"
    rm -rf /etc/clearos/edition/home-7.1.conf
fi
if [ -e /etc/clearos/edition/community-7.1.conf ]; then
    logger -p local6.notice -t installer "app-edition-core - removing Community 7.1 definition"
    rm -rf /etc/clearos/edition/community-7.1.conf
fi

/usr/clearos/apps/edition/deploy/edition-update

# vi: expandtab shiftwidth=4 softtabstop=4 tabstop=4
