<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['edition_app_description'] = 'The Edition Manager provides a quick way to upgrade from Community to Professional on a new install.';
$lang['edition_app_name'] = 'Edition Manager';
$lang['edition_select_edition'] = 'Select Edition';
