<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['edition_app_description'] = 'The Edition Manager provides a selection process to choose the right version for your environment and budget.';
$lang['edition_app_name'] = 'Menedżer edycji';
$lang['edition_currently_running'] = 'Current software version';
$lang['edition_downgrade'] = 'Obniżenie wersji';
$lang['edition_edition'] = 'Edition';
$lang['edition_exec_summary_business'] = 'Professionally supported IT platform for businesses who want to minimize the risk of downtime.';
$lang['edition_exec_summary_community'] = 'Free now, free forever.  Intended for experienced Linux admins or those who like to "tinker".';
$lang['edition_exec_summary_home'] = 'Help spread the word and share ClearOS Home Edition with your friends and family.';
$lang['edition_no_edition_selected'] = 'Proszę wybrać, która edycja systemu zostanie zainstalowana.';
$lang['edition_not_available'] = 'Not available.';
$lang['edition_not_available_during_testing'] = 'Not available during alpha/beta.';
$lang['edition_select_edition'] = 'Wybierz edycję';
$lang['edition_summary_business'] = 'ClearOS Business Edition is developed and maintained by ClearCenter Inc.  If you are looking for a secure, stable and supported IT platform, the Business Edition has access to exclusive business-specific apps and is supported by a group of experienced Linux admin, developers and deployment specialists.';
$lang['edition_summary_community'] = 'ClearOS Community Edition is supported by a community of volunteers donating their time and knowledge via the ClearFoundation.  This support model may not be the best solution for your business or organisation.  Please consider all factors (technical skill, number of users, data sensitivity, resources etc.) when considering using ClearOS Community Edition in a commercial, professional, educational or large-scale deployment.';
$lang['edition_summary_home'] = 'ClearOS Home Edition is ideal for home environments where individuals want more features and integrated cloud services than those that are typically provided by ISP-issued gateways or home-targeted network devices.';
$lang['edition_thank_you'] = 'Thank You for Choosing ClearOS';
$lang['edition_upgrade'] = 'Podniesienie wersji';
